[HAML-Lint] Fix smoke test due to RuboCop
> Error: RuboCop found unsupported Ruby version 2.4 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.4-compatible analysis was dropped after version 1.12.\nSupported versions: 2.5, 2.6, 2.7, 3.0