Check if `master` tag of devon_rex is used on release
For example:

```console
$ bundle exec rake release'[0.36.1]' DRY_RUN=1
git grep --quiet /devon_rex_.+:master images/

Error: Disallow to release with the `master` tag of the devon_rex images.
```