Fix unit test on CI
```
NotImplementedError: HarnessTest::TestProcessor needs to implement `.config_example`
```

https://github.com/sider/runners/pull/2462/checks?check_run_id=2871328428#step:5:278